// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSettings() {
  return window['go']['app']['ConfigService']['GetSettings']();
}

export function SetSettings(arg1) {
  return window['go']['app']['ConfigService']['SetSettings'](arg1);
}
