// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function GetSettings():Promise<app.Settings>;

export function SetSettings(arg1:app.Settings):Promise<void>;
