// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddContact(arg1, arg2) {
  return window['go']['app']['ConfigService']['AddContact'](arg1, arg2);
}

export function DeleteContact(arg1) {
  return window['go']['app']['ConfigService']['DeleteContact'](arg1);
}

export function GetSettings() {
  return window['go']['app']['ConfigService']['GetSettings']();
}

export function IsGovernanceFeatureEnabled() {
  return window['go']['app']['ConfigService']['IsGovernanceFeatureEnabled']();
}

export function ListContacts() {
  return window['go']['app']['ConfigService']['ListContacts']();
}

export function SetAllowMainnetSend(arg1) {
  return window['go']['app']['ConfigService']['SetAllowMainnetSend'](arg1);
}

export function SetAutoReceive(arg1) {
  return window['go']['app']['ConfigService']['SetAutoReceive'](arg1);
}

export function SetChainID(arg1) {
  return window['go']['app']['ConfigService']['SetChainID'](arg1);
}

export function SetShowGovernance(arg1) {
  return window['go']['app']['ConfigService']['SetShowGovernance'](arg1);
}
