// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function AddContact(arg1:string,arg2:string):Promise<Array<app.Contact>>;

export function DeleteContact(arg1:string):Promise<Array<app.Contact>>;

export function GetSettings():Promise<app.Settings>;

export function ListContacts():Promise<Array<app.Contact>>;

export function SetAutoReceive(arg1:boolean):Promise<void>;

export function SetChainID(arg1:number):Promise<void>;

export function SetShowGovernance(arg1:boolean):Promise<void>;
