// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect() {
  return window['go']['app']['NodeService']['Connect']();
}

export function DeleteEmbeddedData() {
  return window['go']['app']['NodeService']['DeleteEmbeddedData']();
}

export function Disconnect() {
  return window['go']['app']['NodeService']['Disconnect']();
}

export function GetBalances() {
  return window['go']['app']['NodeService']['GetBalances']();
}

export function GetEmbeddedInfo() {
  return window['go']['app']['NodeService']['GetEmbeddedInfo']();
}

export function GetNodeConfig() {
  return window['go']['app']['NodeService']['GetNodeConfig']();
}

export function GetTransactions(arg1, arg2) {
  return window['go']['app']['NodeService']['GetTransactions'](arg1, arg2);
}

export function GetUnreceived() {
  return window['go']['app']['NodeService']['GetUnreceived']();
}

export function NodeStatus() {
  return window['go']['app']['NodeService']['NodeStatus']();
}

export function SetNode(arg1) {
  return window['go']['app']['NodeService']['SetNode'](arg1);
}

export function SetNodeMode(arg1) {
  return window['go']['app']['NodeService']['SetNodeMode'](arg1);
}

export function SetNodeURL(arg1, arg2) {
  return window['go']['app']['NodeService']['SetNodeURL'](arg1, arg2);
}

export function StartAutoReceive() {
  return window['go']['app']['NodeService']['StartAutoReceive']();
}

export function StopAutoReceive() {
  return window['go']['app']['NodeService']['StopAutoReceive']();
}
