// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function Disconnect():Promise<void>;

export function GetBalances():Promise<Array<app.TokenBalance>>;

export function GetTransactions(arg1:number,arg2:number):Promise<Array<app.TxRecord>>;

export function GetUnreceived():Promise<Array<app.UnreceivedBlock>>;

export function NodeStatus():Promise<app.NodeStatus>;

export function SetNode(arg1:string):Promise<void>;

export function StartAutoReceive():Promise<void>;

export function StopAutoReceive():Promise<void>;
