// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function Connect():Promise<void>;

export function DeleteEmbeddedData():Promise<void>;

export function Disconnect():Promise<void>;

export function GetBalances():Promise<Array<app.TokenBalance>>;

export function GetEmbeddedInfo():Promise<app.EmbeddedInfo>;

export function GetNodeConfig():Promise<app.NodeConfig>;

export function GetTransactions(arg1:number,arg2:number):Promise<app.TxPage>;

export function GetUnreceived():Promise<Array<app.UnreceivedBlock>>;

export function NodeStatus():Promise<app.NodeStatus>;

export function SetNodeMode(arg1:string):Promise<void>;

export function SetNodeURL(arg1:string,arg2:string):Promise<void>;

export function StartAutoReceive():Promise<void>;

export function StopAutoReceive():Promise<void>;
