// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Disconnect() {
  return window['go']['app']['NodeService']['Disconnect']();
}

export function GetBalances() {
  return window['go']['app']['NodeService']['GetBalances']();
}

export function GetTransactions(arg1, arg2) {
  return window['go']['app']['NodeService']['GetTransactions'](arg1, arg2);
}

export function GetUnreceived() {
  return window['go']['app']['NodeService']['GetUnreceived']();
}

export function NodeStatus() {
  return window['go']['app']['NodeService']['NodeStatus']();
}

export function SetNode(arg1) {
  return window['go']['app']['NodeService']['SetNode'](arg1);
}

export function StartAutoReceive() {
  return window['go']['app']['NodeService']['StartAutoReceive']();
}

export function StopAutoReceive() {
  return window['go']['app']['NodeService']['StopAutoReceive']();
}
