// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckPillarName(arg1) {
  return window['go']['app']['NomService']['CheckPillarName'](arg1);
}

export function EstimatePlasma(arg1) {
  return window['go']['app']['NomService']['EstimatePlasma'](arg1);
}

export function GetAction(arg1) {
  return window['go']['app']['NomService']['GetAction'](arg1);
}

export function GetActions(arg1, arg2) {
  return window['go']['app']['NomService']['GetActions'](arg1, arg2);
}

export function GetActivePillarCount() {
  return window['go']['app']['NomService']['GetActivePillarCount']();
}

export function GetDelegation() {
  return window['go']['app']['NomService']['GetDelegation']();
}

export function GetDepositedQsr() {
  return window['go']['app']['NomService']['GetDepositedQsr']();
}

export function GetFusionEntries() {
  return window['go']['app']['NomService']['GetFusionEntries']();
}

export function GetMyPillar() {
  return window['go']['app']['NomService']['GetMyPillar']();
}

export function GetMyProjects() {
  return window['go']['app']['NomService']['GetMyProjects']();
}

export function GetMyTokens() {
  return window['go']['app']['NomService']['GetMyTokens']();
}

export function GetPhase(arg1) {
  return window['go']['app']['NomService']['GetPhase'](arg1);
}

export function GetPillarDepositedQsr() {
  return window['go']['app']['NomService']['GetPillarDepositedQsr']();
}

export function GetPillarList() {
  return window['go']['app']['NomService']['GetPillarList']();
}

export function GetPillarQsrCost() {
  return window['go']['app']['NomService']['GetPillarQsrCost']();
}

export function GetPillarReward() {
  return window['go']['app']['NomService']['GetPillarReward']();
}

export function GetPlasmaInfo() {
  return window['go']['app']['NomService']['GetPlasmaInfo']();
}

export function GetProject(arg1) {
  return window['go']['app']['NomService']['GetProject'](arg1);
}

export function GetProjects(arg1, arg2) {
  return window['go']['app']['NomService']['GetProjects'](arg1, arg2);
}

export function GetSentinel() {
  return window['go']['app']['NomService']['GetSentinel']();
}

export function GetSentinelReward() {
  return window['go']['app']['NomService']['GetSentinelReward']();
}

export function GetStakeList() {
  return window['go']['app']['NomService']['GetStakeList']();
}

export function GetTokenByZts(arg1) {
  return window['go']['app']['NomService']['GetTokenByZts'](arg1);
}

export function GetUncollectedReward() {
  return window['go']['app']['NomService']['GetUncollectedReward']();
}

export function GetVotableForMyPillars() {
  return window['go']['app']['NomService']['GetVotableForMyPillars']();
}

export function GetVotablePillars() {
  return window['go']['app']['NomService']['GetVotablePillars']();
}

export function PrepareAddPhase(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['NomService']['PrepareAddPhase'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function PrepareBurn(arg1, arg2) {
  return window['go']['app']['NomService']['PrepareBurn'](arg1, arg2);
}

export function PrepareCancelFuse(arg1) {
  return window['go']['app']['NomService']['PrepareCancelFuse'](arg1);
}

export function PrepareCancelStake(arg1) {
  return window['go']['app']['NomService']['PrepareCancelStake'](arg1);
}

export function PrepareCollectPillarReward() {
  return window['go']['app']['NomService']['PrepareCollectPillarReward']();
}

export function PrepareCollectReward() {
  return window['go']['app']['NomService']['PrepareCollectReward']();
}

export function PrepareCollectSentinelReward() {
  return window['go']['app']['NomService']['PrepareCollectSentinelReward']();
}

export function PrepareCreateProject(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['NomService']['PrepareCreateProject'](arg1, arg2, arg3, arg4, arg5);
}

export function PrepareDelegate(arg1) {
  return window['go']['app']['NomService']['PrepareDelegate'](arg1);
}

export function PrepareDepositQsr(arg1) {
  return window['go']['app']['NomService']['PrepareDepositQsr'](arg1);
}

export function PrepareDonate(arg1, arg2) {
  return window['go']['app']['NomService']['PrepareDonate'](arg1, arg2);
}

export function PrepareExecuteAction(arg1) {
  return window['go']['app']['NomService']['PrepareExecuteAction'](arg1);
}

export function PrepareFuse(arg1, arg2) {
  return window['go']['app']['NomService']['PrepareFuse'](arg1, arg2);
}

export function PrepareGovernanceVote(arg1, arg2, arg3) {
  return window['go']['app']['NomService']['PrepareGovernanceVote'](arg1, arg2, arg3);
}

export function PrepareIssueToken(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['app']['NomService']['PrepareIssueToken'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function PrepareMint(arg1, arg2, arg3) {
  return window['go']['app']['NomService']['PrepareMint'](arg1, arg2, arg3);
}

export function PreparePillarDepositQsr(arg1) {
  return window['go']['app']['NomService']['PreparePillarDepositQsr'](arg1);
}

export function PreparePillarWithdrawQsr() {
  return window['go']['app']['NomService']['PreparePillarWithdrawQsr']();
}

export function PrepareRegisterPillar(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['NomService']['PrepareRegisterPillar'](arg1, arg2, arg3, arg4, arg5);
}

export function PrepareRegisterSentinel() {
  return window['go']['app']['NomService']['PrepareRegisterSentinel']();
}

export function PrepareRevokePillar(arg1) {
  return window['go']['app']['NomService']['PrepareRevokePillar'](arg1);
}

export function PrepareRevokeSentinel() {
  return window['go']['app']['NomService']['PrepareRevokeSentinel']();
}

export function PrepareStake(arg1, arg2) {
  return window['go']['app']['NomService']['PrepareStake'](arg1, arg2);
}

export function PrepareUndelegate() {
  return window['go']['app']['NomService']['PrepareUndelegate']();
}

export function PrepareUpdatePhase(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['NomService']['PrepareUpdatePhase'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function PrepareUpdatePillar(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['NomService']['PrepareUpdatePillar'](arg1, arg2, arg3, arg4, arg5);
}

export function PrepareUpdateToken(arg1, arg2, arg3, arg4) {
  return window['go']['app']['NomService']['PrepareUpdateToken'](arg1, arg2, arg3, arg4);
}

export function PrepareVote(arg1, arg2, arg3) {
  return window['go']['app']['NomService']['PrepareVote'](arg1, arg2, arg3);
}

export function PrepareWithdrawQsr() {
  return window['go']['app']['NomService']['PrepareWithdrawQsr']();
}
