// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EstimatePlasma(arg1) {
  return window['go']['app']['NomService']['EstimatePlasma'](arg1);
}

export function GetFusionEntries() {
  return window['go']['app']['NomService']['GetFusionEntries']();
}

export function GetPlasmaInfo() {
  return window['go']['app']['NomService']['GetPlasmaInfo']();
}

export function PrepareCancelFuse(arg1) {
  return window['go']['app']['NomService']['PrepareCancelFuse'](arg1);
}

export function PrepareFuse(arg1, arg2) {
  return window['go']['app']['NomService']['PrepareFuse'](arg1, arg2);
}
