// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function CancelPending():Promise<void>;

export function ConfirmPublish():Promise<string>;

export function PrepareSend(arg1:app.SendRequest):Promise<app.SendPreview>;

export function Receive(arg1:string):Promise<string>;

export function RequiresPoW(arg1:app.SendRequest):Promise<boolean>;
