// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AckWalletConnectResult(arg1, arg2) {
  return window['go']['app']['TxService']['AckWalletConnectResult'](arg1, arg2);
}

export function CancelPending(arg1) {
  return window['go']['app']['TxService']['CancelPending'](arg1);
}

export function ReconcileWalletConnectPublication(arg1, arg2) {
  return window['go']['app']['TxService']['ReconcileWalletConnectPublication'](arg1, arg2);
}

export function ConfirmPublish(arg1) {
  return window['go']['app']['TxService']['ConfirmPublish'](arg1);
}

export function ConfirmWalletConnectPublish(arg1) {
  return window['go']['app']['TxService']['ConfirmWalletConnectPublish'](arg1);
}

export function PrepareSend(arg1) {
  return window['go']['app']['TxService']['PrepareSend'](arg1);
}

export function PrepareWalletConnectSend(arg1) {
  return window['go']['app']['TxService']['PrepareWalletConnectSend'](arg1);
}

export function Receive(arg1) {
  return window['go']['app']['TxService']['Receive'](arg1);
}

export function RequiresPoW(arg1) {
  return window['go']['app']['TxService']['RequiresPoW'](arg1);
}
