// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelPending() {
  return window['go']['app']['TxService']['CancelPending']();
}

export function ConfirmPublish() {
  return window['go']['app']['TxService']['ConfirmPublish']();
}

export function PrepareSend(arg1) {
  return window['go']['app']['TxService']['PrepareSend'](arg1);
}

export function Receive(arg1) {
  return window['go']['app']['TxService']['Receive'](arg1);
}

export function RequiresPoW(arg1) {
  return window['go']['app']['TxService']['RequiresPoW'](arg1);
}
