// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function AckWalletConnectResult(arg1:string,arg2:number):Promise<void>;

export function CancelPending(arg1:number):Promise<void>;

export function ConfirmPublish(arg1:number):Promise<string>;

export function ConfirmWalletConnectPublish(arg1:number):Promise<Record<string, any>>;

export function PrepareSend(arg1:app.SendRequest):Promise<app.SendPreview>;

export function PrepareWalletConnectSend(arg1:app.WalletConnectSendRequest):Promise<app.WalletConnectPrepareResult>;

export function ReconcileWalletConnectPublication(arg1:string,arg2:number):Promise<Record<string, any>>;

export function Receive(arg1:string):Promise<string>;

export function RequiresPoW(arg1:app.SendRequest):Promise<boolean>;
