// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CurrentAccounts() {
  return window['go']['app']['WalletService']['CurrentAccounts']();
}

export function ImportKeystore(arg1) {
  return window['go']['app']['WalletService']['ImportKeystore'](arg1);
}

export function ListWallets() {
  return window['go']['app']['WalletService']['ListWallets']();
}

export function Lock() {
  return window['go']['app']['WalletService']['Lock']();
}

export function SelectAccount(arg1) {
  return window['go']['app']['WalletService']['SelectAccount'](arg1);
}

export function Unlock(arg1, arg2) {
  return window['go']['app']['WalletService']['Unlock'](arg1, arg2);
}
