// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function CurrentAccounts():Promise<Array<app.AccountInfo>>;

export function ImportKeystore(arg1:string):Promise<app.WalletMeta>;

export function ListWallets():Promise<Array<app.WalletMeta>>;

export function Lock():Promise<void>;

export function SelectAccount(arg1:number):Promise<void>;

export function Unlock(arg1:string,arg2:string):Promise<void>;
