// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function AddAccount():Promise<Array<app.AccountInfo>>;

export function ChangePassword(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CurrentAccounts():Promise<Array<app.AccountInfo>>;

export function GenerateMnemonic():Promise<string>;

export function ImportKeystore(arg1:string,arg2:string):Promise<app.WalletMeta>;

export function ImportMnemonic(arg1:string,arg2:string,arg3:string):Promise<app.WalletMeta>;

export function ListWallets():Promise<Array<app.WalletMeta>>;

export function Lock():Promise<void>;

export function PickKeystoreFile():Promise<string>;

export function RenameWallet(arg1:string,arg2:string):Promise<void>;

export function RevealMnemonic(arg1:string):Promise<string>;

export function SelectAccount(arg1:number):Promise<app.AccountInfo>;

export function SetAccountLabel(arg1:number,arg2:string):Promise<void>;

export function Unlock(arg1:string,arg2:string):Promise<void>;
