// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAccount() {
  return window['go']['app']['WalletService']['AddAccount']();
}

export function ChangePassword(arg1, arg2, arg3) {
  return window['go']['app']['WalletService']['ChangePassword'](arg1, arg2, arg3);
}

export function CurrentAccounts() {
  return window['go']['app']['WalletService']['CurrentAccounts']();
}

export function GenerateMnemonic() {
  return window['go']['app']['WalletService']['GenerateMnemonic']();
}

export function ImportKeystore(arg1, arg2) {
  return window['go']['app']['WalletService']['ImportKeystore'](arg1, arg2);
}

export function ImportMnemonic(arg1, arg2, arg3) {
  return window['go']['app']['WalletService']['ImportMnemonic'](arg1, arg2, arg3);
}

export function ListWallets() {
  return window['go']['app']['WalletService']['ListWallets']();
}

export function Lock() {
  return window['go']['app']['WalletService']['Lock']();
}

export function NoteActivity() {
  return window['go']['app']['WalletService']['NoteActivity']();
}

export function PickKeystoreFile() {
  return window['go']['app']['WalletService']['PickKeystoreFile']();
}

export function RenameWallet(arg1, arg2) {
  return window['go']['app']['WalletService']['RenameWallet'](arg1, arg2);
}

export function RevealMnemonic(arg1) {
  return window['go']['app']['WalletService']['RevealMnemonic'](arg1);
}

export function SelectAccount(arg1) {
  return window['go']['app']['WalletService']['SelectAccount'](arg1);
}

export function SetAccountLabel(arg1, arg2) {
  return window['go']['app']['WalletService']['SetAccountLabel'](arg1, arg2);
}

export function SetAutoLockMinutes(arg1) {
  return window['go']['app']['WalletService']['SetAutoLockMinutes'](arg1);
}

export function Unlock(arg1, arg2) {
  return window['go']['app']['WalletService']['Unlock'](arg1, arg2);
}
